### ISSUE TITLE
how to train with my own dataset?

### ISSUE THREAD

**Issue by Cabbagehust2507** [hysts/pytorch_image_classification#11]
I have a dataset including many folders, each folder (as a class) contains images. So I want to train with my own dataset but I don't know how to set up my data structure. Thank you so much!

**Comment by hysts** [comment]
Hi, @Cabbagehust2507 

I think you can use [`torchvision.datasets.ImageFolder`](https://pytorch.org/docs/stable/torchvision/datasets.html?highlight=imagefolder#torchvision.datasets.ImageFolder). You need to modify [this file](https://github.com/hysts/pytorch_image_classification/blob/master/pytorch_image_classification/datasets/datasets.py) to make your dataset available in this repository. See [this part](https://github.com/hysts/pytorch_image_classification/blob/master/pytorch_image_classification/datasets/datasets.py#L77-L85).

If your directory is arranged in exactly the same way as ImageNet, which looks like the following, you can use config files for ImageNet like [this](https://github.com/hysts/pytorch_image_classification/blob/master/configs/imagenet/resnet18.yaml) without modifying any code. In that case, you need to specify `dataset.dataset_dir`, `dataset.image_size`, `dataset.n_classes`, etc. in the config file, and you need to keep `dataset.name` as `ImageNet`.
```
.
├── train
│   ├── n01440764
│   │   ├── n01440764_10026.JPEG
│   │   ├── n01440764_10027.JPEG
│   │   ├── n01440764_10029.JPEG
...
│   │   └── n01440764_9981.JPEG
│   ├── n01443537
│   │   ├── n01443537_10007.JPEG
│   │   ├── n01443537_10014.JPEG
│   │   ├── n01443537_10025.JPEG

...
│       ├── n15075141_9993.JPEG
│       └── n15075141_999.JPEG
└── val
    ├── n01440764
    │   ├── ILSVRC2012_val_00000293.JPEG
    │   ├── ILSVRC2012_val_00002138.JPEG
    │   ├── ILSVRC2012_val_00003014.JPEG
...
```

FYI, [here](https://github.com/rwightman/pytorch-image-models) is a great repository for image classification. You might want to take a look at it.

**Comment by Cabbagehust2507** [comment]
@hysts Thank you so much!
