### ISSUE TITLE
Own DataSet

### ISSUE THREAD

**Issue by Sean0719** [hysts/pytorch_image_classification#13]
Hi,

I am a new in this area. Could you please give me some suggestions about how can I train the model using my own dataset. Thanks in advance.

Kind regards,

Sean

**Comment by hysts** [comment]
Hi, @Sean0719 

I think these issues are helpful to your question: https://github.com/hysts/pytorch_image_classification/issues/11 https://github.com/hysts/pytorch_image_classification/issues/12
