### ISSUE TITLE
Slight inaccuracy in VGG model definition?

### ISSUE THREAD

**Issue by ramasesh** [hysts/pytorch_image_classification#20]
First of all, thanks for the great repository!

I think there might be a slight inaccuracy in the way VGG is defined here: https://github.com/hysts/pytorch_image_classification/blob/master/pytorch_image_classification/models/cifar/vgg.py

Specifically, in the `make_stage` function:
```
    def _make_stage(self, in_channels, out_channels, n_blocks):
        stage = nn.Sequential()
        for index in range(n_blocks):
            if index == 0:
                conv = nn.Conv2d(
                    in_channels,
                    out_channels,
                    kernel_size=3,
                    stride=1,
                    padding=1,
                )
            else:
                conv = nn.Conv2d(
                    out_channels,
                    out_channels,
                    kernel_size=3,
                    stride=1,
                    padding=1,
                )
            stage.add_module(f'conv{index}', conv)
            if self.use_bn:
                stage.add_module(f'bn{index}', nn.BatchNorm2d(out_channels))
            stage.add_module('relu', nn.ReLU(inplace=True))
        stage.add_module('pool', nn.MaxPool2d(kernel_size=2, stride=2))
        return stage 
```

I think currently, only one `relu` module is being added, i.e. not one for each value of `index`.  Whereas in the VGG paper, there should be a `relu` for each value of index.  It seems like the fix for this should just be modifying the line:
`stage.add_module('relu', nn.ReLU(inplace=True))`, to make it
`stage.add_module(f'relu{index}', nn.ReLU(inplace=True))`.

**Comment by hysts** [comment]
Hi, @ramasesh 

Ohhh, you're right! I can't believe this bug has been hiding for so long.
Thank you so much!!
