### ISSUE TITLE
how to add more algorithm for imagenet from pytorch-image-models

### ISSUE THREAD

**Issue by wolfryu** [hysts/pytorch_image_classification#21]
Thank you for your excellent work and share !!!

The result of pyramidnet or resnext is very good ! 
However, I want to try some more algorithms such as efficientnet, the github project pytorch-image-models you mentioned before has many algorithms, but the project is build to train and test in open dataset, not good at run our own dataset. Even I changed the code to run my own dataset, the result is worse than your project with the same algorithms.
So, could you give me some advice about how to add efficientnet from pytorch-image-models to your project for imagenet? 
Thanks a lot !!!

**Comment by hysts** [comment]
Hi, @wolfryu 

I think a quick and dirty way to do it is to apply the following changes.

```diff
--- a/train.py
+++ b/train.py
@@ -12,12 +12,12 @@ import torch.distributed as dist
 import torchvision

 from fvcore.common.checkpoint import Checkpointer
+from timm.models import create_model

 from pytorch_image_classification import (
     apply_data_parallel_wrapper,
     create_dataloader,
     create_loss,
-    create_model,
     create_optimizer,
     create_scheduler,
     get_default_config,
@@ -359,7 +359,8 @@ def main():

     train_loader, val_loader = create_dataloader(config, is_train=True)

-    model = create_model(config)
+    model = create_model(config.model.name)
+    model.to(config.device)
     macs, n_params = count_op(config, model)
     logger.info(f'MACs   : {macs}')
     logger.info(f'#params: {n_params}')
```

**Comment by wolfryu** [comment]
Thank you so much!!! I will try this and report the result soon.
