### ISSUE TITLE
how to train use distributed pattern? 

### ISSUE THREAD

**Issue by Gavinic** [hysts/pytorch_image_classification#28]

**Comment by hysts** [comment]
Hi, @Gavinic 

You can use [`torch.distributed.launch` utility](https://pytorch.org/docs/stable/distributed.html#launch-utility) to run ddp training.
[Here](https://github.com/hysts/pytorch_image_classification#using-2-gpus) is a command example.

**Comment by Gavinic** [comment]
> Hi, @Gavinic
> 
> You can use [`torch.distributed.launch` utility](https://pytorch.org/docs/stable/distributed.html#launch-utility) to run ddp training. [Here](https://github.com/hysts/pytorch_image_classification#using-2-gpus) is a command example.

great, thanks.
