### ISSUE TITLE
Very good job, the experiment is very detailed

### ISSUE THREAD

**Issue by hhaAndroid** [hysts/pytorch_image_classification#4]
this

**Comment by hysts** [comment]
Thanks! :)

**Comment by bassbone** [comment]
I feel the same way !

**Comment by change6688** [comment]
After I change the path to the Imagenet dataset, I report an error "override list has odd length: ['/ ljz / data / Imagenet']; It must be a list of pairs ", is it because there are still paths that have not been changed? I would be grateful if you could provide me with solution

**Comment by hysts** [comment]
@change6688 

It seems the error is raised by yacs when the number of the additional command line arguments is an odd number.

The command should look like this:
```bash
python train.py --config config.yaml \
    key1 value1 \
    key2 value2 \
    key3 value3
```
You should check the command you ran again.

BTW, next time, please create a new issue, if the content is irrelevant to the original issue.
Plus, it'd be easier to find the cause of the error if you provide the command you executed and the error message.
