### ISSUE TITLE
how to train custome datasets?

### ISSUE THREAD

**Issue by luolugithub** [hysts/pytorch_image_classification#5]

**Comment by hysts** [comment]
Hi, @luolugithub 
Sorry for the late reply.

I guess it was kind of difficult to train on custom datasets with the older version of this repository. Recently, I updated the repository, and now it's easier to train on custom datasets. You can implement your own dataset class and modify [this](https://github.com/hysts/pytorch_image_classification/blob/master/pytorch_image_classification/datasets/datasets.py#L29) function to use it.
