### ISSUE TITLE
What is WRN20-4 in the results?

### ISSUE THREAD

**Issue by Lidonghao1996** [hysts/pytorch_image_classification#8]
This repo is very detailed and informative, thanks!
However, I have a little bit confused about the WRN20-4 in the results. Since the depth of WRN should satisfy (6*n)+4, and 20 depth is not satisfied. I want to know how to get the result of WRN-20-4?

https://github.com/hysts/pytorch_image_classification#results

Best!

**Comment by hysts** [comment]
Hi, @Lidonghao1996 

Thanks for pointing that out. It's a typo. It should be called `ResNet-20 with a widening factor 4` or `WRN-22-4`.

FYI, WRN notation is a bit confusing. Usually, a notation like ResNet-20 means the depth of the model is 20, while in the WRN paper, they say,

> In the rest of the paper we use the following notation: WRN-n-k denotes a residual network that has a total number of convolutional layers n and a widening factor k

So, if the model uses convolutions to downsample, they're counted as well in WRN notation.
That's the cause of my typo.

I'm going to update README. Thank you!
